- name: create init script directory
  file:
    path: /var/lib/jenkins/init.groovy.d
    state: directory
    owner: jenkins
    group: jenkins

- name: deploy InstallPlugin.groovy
  copy:
    src: InstallPlugin.groovy
    dest: /var/lib/jenkins/init.groovy.d/InstallPlugin.groovy
    owner: jenkins
    group: jenkins
    mode: 0755

- name: jenkinsのsshkeyようディレクトリ作成
  file:
    path: /var/lib/jenkins/.ssh
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0700

- name: jenkinsをrestartして設定を反映
  service: name=jenkins state=restarted
