# wgetが必要なのでインストール
- name: install wget
  yum: name=wget state=latest

# リポジトリを追加
# https://pkg.jenkins.io/redhat-stable/ の手順の通り
- shell: wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
- shell: rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key

- name: install jenkins
  yum: name=jenkins state=latest

# サービスをstart
- name: enable jenkins
  service: name=jenkins state=started enabled=yes

- name: jenkinsユーザーのシェルをbashに変更
  user: name=jenkins state=present shell=/bin/bash
